language: perl
perl:
- '5.22'
sudo: enabled
before_install:
- openssl aes-256-cbc -K $encrypted_e1304e2fcacf_key -iv $encrypted_e1304e2fcacf_iv
  -in .travis/travis_id_rsa.enc -out .travis/travis_id_rsa -d
- wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add -
- echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install fhem -y
install: true
