language: perl
perl:
- '5.22'
sudo: enabled
before_install:
- wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add -
- echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install fhem -y
install: true
after_success:
- .travis/deploy.sh