name: Test on Pull

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup fhem
        run: |
          wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add -
          echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update -qq
          sudo apt-get install fhem -y
      # Runs a single command using the runners shell
      - name: Run Test
        run: make test
